# Generated by Django 4.1.6 on 2023-02-10 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='Person_name',
            new_name='name',
        ),
    ]
